---
title: ""
self_contained: yes
runtime: shiny
---

<br>

# Baseline conditions {.tabset}

```{r setup, include = FALSE}
# globals
library(knitr)
opts_chunk$set(echo = F, message = F, warning = F)

library(tidyverse)
library(sf)
library(mapview)
library(shiny)
library(leaflet)
library(randomForest)

# prj <- 4326 # geographic wgs84
prj <- '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'

source('R/funcs.R')

data(rchdat)
data(biodat)
data(bsflowmetest)
data(bstmpmetest)
data(metmods)

# color palette function for prob map
pal <- colorNumeric(
  palette = RColorBrewer::brewer.pal(11, 'Spectral'),
  na.color = NA,
  domain = c(0, 1)
)

rchdat <- rchdat %>% 
  st_transform(crs = prj)
```

```{r mastinp}
column(width = 12,

       column(width = 4, 
              
              # select species to show
              selectInput("spmap", "Choose species:", sort(unique(biodat$name)))
                
        ), 
       
       column(width = 4,
              
              # select metric type
              selectInput("mettyp", "Select predictor type:", choices = c('Flow', 'Temperature'))
       
        ),
       
       column(width = 4, 
              
              renderUI({
                
                # input
                mettyp <- input$mettyp
                
                if(mettyp == 'Flow')
                  sels <- list(dry = '2014-07-01', moderate = '2010-07-01', wet = '1993-07-01')
                
                if(mettyp == 'Temperature')
                  sels <- bstmpmetest %>% pull(year) %>% unique %>% sort
                
                selectInput('bstyp', 'Select baseline conditions:', choices = sels)
                
              })
              
        )
       
)
```

```{r reactives}
# model to use from species selection and metric type selection
spmod <- reactive({
  
  # input
  spmap <- input$spmap
  mettyp <- input$mettyp
  
  req(spmap)
  
  modnm <- gsub('^.*\\s(.*)$', '\\1', spmap)
  
  if(mettyp == 'Flow')
    modnm <- modnm %>% 
      paste0('mod_', ., '_rf')
  
  if(mettyp == 'Temperature')
    modnm <- modnm %>% 
      paste0(., '_mdl')
    
  out <- metmods[[modnm]]
  
  return(out)
  
})

# baseline metrics to use
bsmets <- reactive({
  
  # input
  bstyp <- input$bstyp
  mettyp <- input$mettyp
  
  req(bstyp)
  
  # filter baseline metrics by year selection
  if(mettyp == 'Flow'){
    
    req(bstyp %in% as.character(bsflowmetest$dtsl))
    
    out <- bsflowmetest %>% 
      filter(dtsl %in% as.Date(bstyp)) %>% 
      dplyr::select(var, COMID, est) %>% 
      spread(var, est)
    
  }
  
  if(mettyp == 'Temperature'){
    
    req(bstyp %in% bstmpmetest$year)
    
    out <- bstmpmetest %>% 
      filter(year %in% bstyp)
    
  }
  
  return(out)
  
})

# probability of occurrence predictions for species and baseline condition
bsprds <- reactive({
  
  # input
  spmod <- spmod()
  bsmets <- bsmets()
  mettyp <- input$mettyp
  
  if(mettyp == 'Flow')
    prds <- predict(spmod, newdata = bsmets, type = 'prob')[, 1, drop = T]
  
  if(mettyp == 'Temperature')
    prds <- predict(spmod, newdata = bsmets, type = 'response')
  
  # get predictions by comid
  out <- bsmets %>% 
    mutate(
      procc = prds
    ) %>% 
    dplyr::select(COMID, procc)
  
  return(out)
  
})

# map of predictions by comid 
bsprdsmap <- reactive({
  
  # input
  bsprds <- bsprds()
  
  tomap <- rchdat %>% 
    left_join(bsprds, by = 'COMID')

  mapview(tomap, layer.name = 'reset') %>% 
    .@map

})
```

```{r}
output$bsprdsmap <- renderLeaflet({bsprdsmap()})
```
```{r}
leafletOutput('bsprdsmap')

observe({
    
    input$spmap
    
    # reactives
    bsprds <- bsprds()
  
    tomap <- rchdat %>% 
      left_join(bsprds, by = 'COMID')

    # spp prob map
    mapout <- leafletProxy("bsprdsmap", data = tomap) %>%
      clearMarkers() %>%
      clearShapes() %>%
      clearControls() %>%
      addPolylines(opacity = 1, weight = 1, color = ~pal(procc)) %>% 
      # label = ~paste0(COMID, ', Likely score:', as.character(round(lns, 2)))
      # ) %>%
      addLegend("topright", pal = pal, values = ~procc,
                title = "Pr. occurence", opacity = 1
      )

})
  
```



