---
title: ""
self_contained: yes
runtime: shiny
---

<br>

# Observed biology {.tabset}

```{r setup, include = FALSE}
# globals
library(knitr)
opts_chunk$set(echo = F, message = F, warning = F)

library(tidyverse)
library(sf)
library(mapview)
library(shiny)
library(leaflet)
library(stargazer)

source('R/funcs.R')

data(biodat)
data(rchdat)
data(bioflowmetest)
data(biotmpmet)
```

```{r mastinp}
column(width = 12,

       column(width = 4, 
              
              # select species to show
              selectInput("spmap", "Choose species:", sort(unique(biodat$name)))
                
        ), 
       
       column(width = 4,
              
              # select metric type
              selectInput("mettyp", "Select predictor type:", choices = c('Flow', 'Temperature'))
       
        ),
       
       column(width = 4, 
              
              renderUI({
                
                # input
                mettyp <- input$mettyp
                
                if(mettyp == 'Flow'){
                  tosel <- names(bioflowmetest)
                }
              
                if(mettyp == 'Temperature'){
                  tosel <- names(biotmpmet)
                }
                
                tosel <- tosel[!tosel %in% c('name', 'COMID', 'date', '<NA>', 'year', 'occurrence')]
                
                selectInput("metsel", "Select meric:", choices = tosel)
                
              })
              
        )
       
)
```

```{r reactives}
# species selection
sprct <- reactive({
  
  # input
  spmap <- input$spmap
  
  out <- biodat %>% 
    filter(name %in% spmap) 
  
  return(out)
  
})

# map of species data
spmap <- reactive({
  
  # input
  sprct <- sprct()
  
  # get pt size
  occex <- sprct$occex
  
  # colors
  cols <- c('tomato1', 'lightgreen')
  names(cols) <- c('absent', 'present')
  
  out <- mapview(rchdat, homebutton = F, color = 'black', legend = F, lwd = 0.5, alpha = 0.5, layer = 'Reaches') + 
    mapview(sprct, zcol = 'occurrence', legend = T, col.regions = cols, cex = occex, homebutton = F, layer = 'Occurrence')

  return(out)
 
})

# metric data joined with biodat, biodat COMIDs filtered by rchdat COMID
spmtdat <- reactive({
  
  # input
  metsel <- input$metsel
  mettyp <- input$mettyp
  spmap <- input$spmap
  sprct <- sprct()
  
  req(!is.null(metsel))
      
  if(mettyp == 'Flow'){
  
    req(metsel %in% names(bioflowmetest))
    
    # filter metrics
    mtdat <- bioflowmetest %>% 
      dplyr::select(name, COMID, date, !!metsel) %>% 
      filter(name %in% spmap)
  
    # join species and flow metric data
    out <- sprct %>% 
      filter(COMID %in% rchdat$COMID) %>% 
      left_join(mtdat, by = c('name', 'date', 'COMID')) %>% 
      st_set_geometry(NULL) %>% 
      mutate(
        occurrence = factor(occurrence, levels = c('absent', 'present'))
      ) %>% 
      unique
    
  } 
      
  if(mettyp == 'Temperature'){
    
    req(metsel %in% names(biotmpmet))

    # filter metrics
    out <- biotmpmet %>% 
      mutate(
        occurrence = factor(occurrence, levels = c('0', '1'), labels = c('absent', 'present'))
      ) %>% 
      dplyr::select(name, COMID, year, occurrence, !!metsel) %>% 
      filter(name %in% spmap) %>% 
      filter(COMID %in% rchdat$COMID) 
    
  }
    
  # minor format for output
  out <- out %>% 
    filter(!is.na(occurrence)) %>% 
    mutate(
      occurrbin = case_when(
        occurrence %in% 'absent' ~ 0, 
        occurrence %in% 'present' ~ 1
      )
    ) %>% 
    rename(val = !!metsel)
  
  return(out)
  
})

# metric and biodata plot
spmtplt <- reactive({
  
  # input
  spmtdat <- spmtdat()
  metsel <- input$metsel
  
  p <- ggplot(spmtdat, aes(x = val, y = as.numeric(occurrbin))) +
    geom_point(aes(fill = occurrence), size = 4, alpha = 0.7, pch = 21) +
    scale_fill_manual('Occcurence', values = c('tomato1', 'lightgreen'), drop = FALSE) +
    geom_smooth(method = "glm", method.args = list(family = "binomial"), fullrange = T) +
    theme_bw(base_family = 'serif', base_size = 16) +
    theme(
      legend.title = element_blank(),
      strip.background = element_blank(),
      legend.position = 'top'
      ) +
    ylab('Pr. occurrence') + 
    xlab(metsel)
  
  return(p)
  
})

# regression mod for spmtplt
spmtmod <- reactive({
  
  # inputs
  spmtdat <- spmtdat()
  
  mod <- glm(occurrbin ~ val, spmtdat, family = 'binomial')
  
  return(mod)
  
})
```

## Observed data

```{r spmap}
# mapview
output$spmap <- renderLeaflet({spmap()@map})
```
```{r}
leafletOutput('spmap')
```

## Modelled response

```{r}
output$spmtplt <- renderPlot({spmtplt()}, width = 500, height = 500)
```
```{r}
column(12,
  column(width = 6, 
         plotOutput('spmtplt')
  ), 
  column(width = 6,
          HTML('<br>'), 
          renderUI({
            
            # input
            spmtmod <- spmtmod()
            metsel <- input$metsel
            
            cvars <- c(metsel, 'intercept')
          
            spmtmod %>%
              stargazer(., type = 'html', dep.var.labels = 'presence/absence', covariate.labels = c('metric', 'intercept')) %>% 
              HTML
            
          })
  )
)
```

