---
title: ""
self_contained: yes
runtime: shiny
---

<br>

## Future scenarios {.tabset}

```{r setup, include = FALSE}
# globals
library(knitr)
opts_chunk$set(echo = F, message = F, warning = F)

library(tidyverse)
library(sf)
library(mapview)
library(shiny)
library(leaflet)
library(randomForest)

# prj <- 4326 # geographic wgs84
prj <- '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'

source('R/funcs.R')

data(rchdat)
data(futest)

# color palette function for prob map
pal <- colorNumeric(
  palette = RColorBrewer::brewer.pal(11, 'Spectral'),
  na.color = NA,
  domain = c(0, 1)
)

rchdat <- rchdat %>% 
  st_transform(crs = prj)
```

```{r mastinp}
column(width = 12,

       column(width = 4, 
              
              # select species to show
              selectInput("spmap", "Choose species:", sort(unique(futest$spp)))
                
        ), 
       
       column(width = 4,
              
              # select metric type
              selectInput("clmmod", "Select climate change model", choices = list(CanESM2 = 'CanESM2', CCSM4 = 'CCSM4', MIROC5 = 'MIROC5'))
       
        ),
       
       column(width = 4, 
              
              # select model year  
              selectInput("futyr", 'Select future year:', choices = c("2040" = 'dt1', "2100" = 'dt2'))
              
        )
       
)
```

```{r reactives}
# future predictions for selection
futprds <- reactive({
  
  # input
  spmap <- input$spmap
  clmmod <- input$clmmod
  futyr <- input$futyr
  
  # filter predictions by selection
  out <- futest %>% 
    filter(spp %in% spmap) %>% 
    filter(mds %in% clmmod) %>% 
    filter(futyr %in% futyr)
  
  return(out)
  
})


# map of predictions by comid 
futprdsmap <- reactive({
  
  # input
  futprds <- futprds()
  
  tomap <- rchdat %>% 
    left_join(futprds, by = 'COMID')

  mapview(tomap, layer.name = 'reset') %>% 
    .@map

})
```

```{r}
output$futprdsmap <- renderLeaflet({futprdsmap()})
```
```{r}
leafletOutput('futprdsmap')

observe({
    
    input$spmap
    
    # reactives
    futprds <- futprds()
  
    tomap <- rchdat %>% 
      left_join(futprds, by = 'COMID')

    # spp prob map
    mapout <- leafletProxy("futprdsmap", data = tomap) %>%
      clearMarkers() %>%
      clearShapes() %>%
      clearControls() %>%
      addPolylines(opacity = 1, weight = 1, color = ~pal(allprd)) %>% 
      # label = ~paste0(COMID, ', Likely score:', as.character(round(lns, 2)))
      # ) %>%
      addLegend("topright", pal = pal, values = ~allprd,
                title = "Pr. occurence", opacity = 1
      )

})
  
```