---
title: "Biological response of stream communities to climate change"
self_contained: yes
output: html_document
---

### Overview

This website is an interactive tool to demonstrate riparian and stream community responses to changes in hydrology in the Los Angeles and Ventura County watersheds, California, USA.  Biological response was modelled as a function of baseline and projected changes in temperature and flow using historical data and expected flow changes from down-scaled climate change models. This website is provided to enhance understanding of climate change effects on riparian dependent species to facilitate management of watershed, riparian, and in-stream habitats. 

### Objectives and approach 

The objective of this website is to present the project results in a way that is meaningful to the interests of the advisory committee and others that can benefit from this project.  The website is designed to address the following questions:

* What historical biological or baseline flow data are relevant for regulatory or management communities to understand current conditions? 

* What changes in biological communities and flow are relevant for regulatory or management decisions in the region?

* What sources of uncertainty are of most concern to inform decision-making processes?

The website is structured following an analysis workflow that describes the biology, modelled hydrology, and biological response to flow changes. Data can viewed using different selection widgets and downloaded in tabular or graphical format. __The tabs at the top of the website link to separate components of the analysis.__

1) __Biological data__: View and download biology data for the Los Angeles and Ventura County watersheds, historical data from existing surveys

1) __Modelled flow data__: View and download flow data for the Los Angeles and Ventura County watersheds, historical and projected climate change scenarios

1) __Biological response to flow__: View and download biological responses to flow, baseline and projected climate change scenarios

### Attribution

All site content and analyses by [Marcus Beck](mailto:marcusb@sccwrp.org), with assistance from [Jenny Taylor](mailto:jennyt@sccwrp.org), [Abel Santana](mailto:abels@sccwrp.org), and [Eric Stein](mailto:erics@sccwrp.org). Click the icon on the top left to view the web page source content.
